#!/bin/sh
#
# @name Gazebo x500 depth
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_depth}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Powerplant mission uses ROS external vision indoors: no GPS, no compass,
# no manual-control source, and Gazebo odometry/dynamic pose for truth.
param set-default EKF2_EV_CTRL 11
param set-default EKF2_HGT_REF 3
param set-default EKF2_GPS_CTRL 0
param set-default SYS_HAS_GPS 0
param set-default SYS_HAS_MAG 0
param set-default EKF2_MAG_TYPE 5
param set-default SIM_GZ_EN_ODOM 1
param set-default COM_RC_IN_MODE 4
param set-default COM_ARM_WO_GPS 2
param set-default COM_ARM_ODID 0
param set-default COM_HOME_IN_AIR 1
